# Generated by Django 4.2.4 on 2023-09-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Category_description', models.CharField(blank=True, max_length=200, null=True)),
                ('Category_image', models.ImageField(blank=True, null=True, upload_to='Category image')),
            ],
        ),
    ]
