# Generated by Django 4.2.4 on 2023-10-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoApp', '0002_productdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('c_address', models.CharField(blank=True, max_length=100, null=True)),
                ('c_city', models.CharField(blank=True, max_length=100, null=True)),
                ('c_Country', models.CharField(blank=True, max_length=100, null=True)),
                ('c_zipcode', models.IntegerField(blank=True, null=True)),
                ('c_phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
