# Generated by Django 4.2.4 on 2023-10-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoApp', '0003_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='frndlogindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('u_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
