# Generated by Django 4.2.4 on 2023-10-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoApp', '0005_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cartdb',
        ),
    ]
